Repository mother/oio-react, pull requests merged in 2019-07, with the labels that each got.

#4 Button
  docs/pages/API/Button/index.js
  docs/pages/API/index.js
  docs/pages/Tests/index.js
  docs/specimens/ButtonChildren/index.js
  docs/specimens/ButtonCustomizations/index.js
  docs/specimens/ButtonModes/index.js
  docs/specimens/ButtonSizes/index.js
  docs/specimens/ButtonStyles/index.js
  package-lock.json
  package.json
  src/Button/index.js
  src/Button/spec.js
  src/OIOProvider/context.js
  src/OIOProvider/index.js
  src/Spinner/index.js
  src/index.js
  tests/components/OIOProvider/__snapshots__/index.js.snap
  tests/visual/Button.js
  tests/visual/screenshots/Button.js/Button Children.snap.png
  tests/visual/screenshots/Button.js/Button Customizations.snap.png
  tests/visual/screenshots/Button.js/Button Sizes.snap.png
  tests/visual/screenshots/Button.js/Button Styles.snap.png
  tests/visual/screenshots/OIOProvider.js/Normalized Styles.snap.png
Labels: 3pt, ready for review

#27 Grid + GridCell
  docs/assets/dot.png
  docs/assets/land.jpeg
  docs/assets/nyc-public-lib.jpeg
  docs/pages/API/Grid/index.js
  docs/pages/Tests/index.js
  docs/server.js
  docs/specimens/GridBasic/index.js
  docs/specimens/GridCellBackgroundImage/index.js
  docs/specimens/GridResponsive/index.js
  package-lock.json
  src/Grid/index.js
  src/Grid/spec.js
  src/GridCell/index.js
  src/GridCell/specAppearance.js
  src/GridCell/specBasic.js
  tests/visual/Grid.js
  tests/visual/screenshots/Grid.js/Grid [a].snap.png
  tests/visual/screenshots/Grid.js/Grid [b].snap.png
  tests/visual/screenshots/Grid.js/Grid [c].snap.png
  tests/visual/screenshots/Grid.js/Grid [d].snap.png
  tests/visual/screenshots/Grid.js/Grid [e].snap.png
  tests/visual/screenshots/Grid.js/Grid [f].snap.png
  tests/visual/screenshots/Grid.js/GridCell Background Image.snap.png
Labels: 2pt, ready for review

#26 Spacer
  docs/pages/API/Spacer/index.js
  docs/pages/API/index.js
  docs/pages/Tests/index.js
  docs/specimens/SpacerHorizontal/index.js
  docs/specimens/SpacerVertical/index.js
  src/Spacer/index.js
  src/Spacer/spec.js
  src/index.js
  tests/visual/Spacer.js
  tests/visual/screenshots/Spacer.js/Spacer Horizontal.snap.png
  tests/visual/screenshots/Spacer.js/Spacer Vertical.snap.png
Labels: 2pt, ready for review

#31 Dependency Upgrades
  config/jest/setup.js
  package-lock.json
  package.json
Labels: 1pt, ready for review

#32 OIO Form Component
  docs/pages/API/Form/index.js
  docs/specimens/FormInputSizes/index.js
  docs/specimens/FormOutline/index.js
  docs/specimens/FormPlain/index.js
  src/Form/Checkbox/index.js
  src/Form/Checkbox/spec.js
  src/Form/Input/index.js
  src/Form/Input/spec.js
  src/Form/Label/index.js
  src/Form/Radio/index.js
  src/Form/Radio/spec.js
  src/Form/Select/index.js
  src/Form/Select/spec.js
  src/Form/Switch/index.js
  src/Form/Switch/spec.js
  src/Form/Textarea/index.js
  src/Form/Textarea/spec.js
  src/Form/index.js
  src/Form/spec.js
  src/OIOProvider/index.js
  src/index.js
  tests/components/OIOProvider/__snapshots__/index.js.snap
Labels: ready for review

#29 Form
  config/webpack/build.js
  config/webpack/dev.js
  docs/components/APITableBlock/index.js
  docs/pages/API/Button/index.js
  docs/pages/API/Form/index.js
  docs/pages/API/index.js
  docs/pages/API/style.less
  docs/pages/Tests/index.js
  docs/specimens/ButtonSizes/index.js
  docs/specimens/FormInputSizes/index.js
  docs/specimens/FormInputUnderline/index.js
  docs/specimens/FormOutline/index.js
  docs/specimens/FormPlain/index.js
  docs/specimens/GridCellBackgroundImage/index.js
  package-lock.json
  package.json
  src/Button/index.js
  src/Form/Checkbox/checkboxIcon.svg
  src/Form/Checkbox/index.js
  src/Form/Checkbox/spec.js
  src/Form/Input/index.js
  src/Form/Input/spec.js
  src/Form/Label/index.js
  src/Form/Label/spec.js
  src/Form/Radio/index.js
  src/Form/Radio/spec.js
  src/Form/Select/index.js
  src/Form/Select/selectArrowIcon.svg
  src/Form/Select/spec.js
  src/Form/Switch/index.js
  src/Form/Switch/spec.js
  src/Form/Textarea/index.js
  src/Form/Textarea/spec.js
  src/Form/index.js
  src/Form/spec.js
  src/OIOProvider/index.js
  src/index.js
  tests/visual/Form.js
  tests/visual/screenshots/Button.js/Button Children.snap.png
  tests/visual/screenshots/Button.js/Button Customizations.snap.png
  tests/visual/screenshots/Button.js/Button Sizes.snap.png
  tests/visual/screenshots/Button.js/Button Styles.snap.png
  tests/visual/screenshots/Form.js/Form - Outline Appearance.snap.png
  tests/visual/screenshots/Form.js/Form - Plain Appearance.snap.png
  tests/visual/screenshots/Form.js/Input - Sizes.snap.png
  tests/visual/screenshots/Form.js/Input - Underline Appearance.snap.png
  tests/visual/screenshots/Grid.js/GridCell Background Image.snap.png
Labels: 5pt, ready for review

#30 NotificationInline
  docs/pages/API/NotificationInline/index.js
  docs/pages/API/index.js
  docs/pages/API/style.less
  docs/pages/Tests/index.js
  docs/specimens/NotificationInlineCustomized/index.js
  docs/specimens/NotificationInlineTypes/index.js
  src/NotificationInline/index.js
  src/NotificationInline/spec.js
  src/assets/icons/checkmarkCircled.js
  src/assets/icons/closeCircled.js
  src/assets/icons/infoCircled.js
  src/assets/icons/questionCircled.js
  src/assets/icons/warningCircled.js
  src/index.js
  tests/visual/NotificationInline.js
  tests/visual/screenshots/Grid.js/GridCell Background Image.snap.png
  tests/visual/screenshots/NotificationInline.js/NotificationInline - Customized.snap.png
  tests/visual/screenshots/NotificationInline.js/NotificationInline - Types.snap.png
Labels: 3pt, ready for review

#37 Optional Chaining & Multiplier Utility
  .babelrc
  package-lock.json
  package.json
  src/Button/index.js
  src/utils/applyMultiplier.js
  tests/utils/applyMultiplier/index.js
Labels: 1pt, ready for review
