Repository mother/oio-react, pull requests merged in 2019-09, with the labels that each got.

#41 Forward refs for all form elements
  src/Form/Checkbox/index.js
  src/Form/Input/index.js
  src/Form/Radio/index.js
  src/Form/Select/index.js
  src/Form/Switch/index.js
  src/Form/Textarea/index.js
Labels: 1pt, ready for review

#40 Modal
  config/constants.js
  docs/pages/API/Modal/index.js
  docs/pages/API/index.js
  docs/specimens/ModalBasic/index.js
  docs/specimens/ViewEvents/index.js
  package-lock.json
  src/Modal/index.js
  src/Modal/spec.js
  src/Modal/style.js
  src/OIOProvider/index.js
  src/OIOProvider/spec.js
  src/View/index.js
  src/index.js
  tests/components/OIOProvider/__snapshots__/index.js.snap
  tests/components/OIOProvider/index.js
  tests/components/Text/__snapshots__/index.js.snap
  tests/components/Text/index.js
  tests/visual/Modal.js
  tests/visual/screenshots/Modal.js/Modal - Close.snap.png
  tests/visual/screenshots/Modal.js/Modal - Open.snap.png
Labels: 2pt, ready for review

#48 Popover Anchor Element
  docs/pages/API/Popover/index.js
  docs/specimens/PopoverBasic/index.js
  docs/specimens/PopoverOpen/index.js
  package-lock.json
  src/Button/index.js
  src/Popover/index.js
  src/Popover/spec.js
Labels: 1pt, ready for review

#42 Popover
  docs/components/SpecimenBlock/index.js
  docs/pages/API/Popover/index.js
  docs/pages/API/index.js
  docs/specimens/PopoverBasic/index.js
  docs/specimens/PopoverOpen/index.js
  docs/specimens/ViewKitchenSink/index.js
  package-lock.json
  src/Button/index.js
  src/Form/Switch/index.js
  src/ListMenuButton/index.js
  src/Modal/index.js
  src/Popover/index.js
  src/Popover/spec.js
  src/Popover/style.js
  src/View/index.js
  src/View/spec.js
  src/index.js
  tests/visual/Popover.js
  tests/visual/screenshots/NotificationInline.js/NotificationInline - Customized.snap.png
  tests/visual/screenshots/Popover.js/Popover - Close.snap.png
  tests/visual/screenshots/Popover.js/Popover - Open.snap.png
Labels: 2pt, ready for review

#49 OIOTransformer & useWindowResizeSensor
  docs/pages/API/OIOTransformer/index.js
  docs/pages/API/index.js
  docs/specimens/OIOTransformer/index.js
  package-lock.json
  src/OIOTransformer/index.js
  src/OIOTransformer/spec.js
  src/index.js
  src/utils/useWindowResizeSensor.js
  tests/visual/OIOTransformer.js
  tests/visual/screenshots/OIOTransformer.js/OIO Transformer - Modal.snap.png
  tests/visual/screenshots/OIOTransformer.js/OIO Transformer - Popover.snap.png
Labels: 2pt, ready for review

#51 Popover Updates
  docs/specimens/PopoverBasic/index.js
  docs/specimens/PopoverOpen/index.js
  package-lock.json
  src/Popover/index.js
  src/Popover/spec.js
  tests/visual/Popover.js
  tests/visual/screenshots/Popover.js/Popover - Close.snap.png
  tests/visual/screenshots/Popover.js/Popover - Open (left top).snap.png
  tests/visual/screenshots/Popover.js/Popover - Open (right bottom).snap.png
  tests/visual/screenshots/Popover.js/Popover - Open.snap.png
Labels: 2pt, ready for review

#50 Button Links
  docs/index.js
  docs/pages/API/Button/index.js
  docs/pages/API/ListMenu/index.js
  docs/pages/API/OIOProvider/index.js
  docs/specimens/ButtonLink/index.js
  docs/specimens/ListMenuLinks/index.js
  docs/specimens/OIOProviderComponent/index.js
  docs/specimens/OIOProviderReactRouter/index.js
  src/Button/index.js
  src/Button/spec.js
  src/ListMenu/index.js
  src/ListMenuButton/index.js
  src/ListMenuButton/spec.js
  src/OIOProvider/buttonLinkAdapterSpec.js
  src/OIOProvider/index.js
  src/OIOProvider/spec.js
  tests/components/OIOProvider/__snapshots__/index.js.snap
  tests/visual/Button.js
  tests/visual/ListMenu.js
  tests/visual/screenshots/Button.js/Button Link.snap.png
  tests/visual/screenshots/ListMenu.js/ListMenu - with menu button links.snap.png
Labels: 3pt, ready for review

#52 useWindowResizeSensor - breakpoint detection fix
  config/constants.js
  src/utils/useWindowResizeSensor.js
  tests/utils/useWindowResizeSensor/index.js
Labels: 1pt, ready for review
