Repository mother/oio-react, pull requests merged in 2019-03, with the labels that each got.

#18 Cypress Config and Command
  .gitignore
  config/.eslintrc
  config/cypress/cypress.json
  config/cypress/support/index.js
  package-lock.json
  package.json
  tests/visual/OIOProvider.js
  tests/visual/screenshots/OIOProvider.js/Normalized Styles.snap.png
Labels: 1pt, in review, ready for review

#19 updated jest config
  config/jest/config.js
  package-lock.json
Labels: ready for review

#2 Text (merge # 18 first)
  .babelrc
  .eslintrc
  config/jest/.eslintrc
  config/jest/setup.js
  docs/pages/API/OIOProvider/index.js
  docs/pages/API/Text/index.js
  docs/pages/API/index.js
  docs/pages/API/style.less
  docs/pages/Tests/index.js
  docs/specimens/TextAutoScale/index.js
  docs/specimens/TextColors/index.js
  docs/specimens/TextSizes/index.js
  docs/specimens/TextWeights/index.js
  package-lock.json
  package.json
  src/OIOProvider/context.js
  src/OIOProvider/index.js
  src/OIOProvider/normalizationStyles.js
  src/Text/index.js
  src/index.js
  src/utils/withDynamicResponsiveProps.js
  tests/components/OIOProvider/__snapshots__/index.js.snap
  tests/components/OIOProvider/index.js
  tests/components/Text/__snapshots__/index.js.snap
  tests/components/Text/index.js
  tests/fixtures/breakpoints.js
  tests/visual/Text.js
  tests/visual/screenshots/Text.js/Text Colors.snap.png
  tests/visual/screenshots/Text.js/Text Sizes.snap.png
  tests/visual/screenshots/Text.js/Text Weights.snap.png
Labels: 5pt, in review, ready for review

#20 Breakpoints
  .travis.yml
  config/constants.js
  src/index.js
  src/utils/generateResponsiveStyles.js
Labels: 1pt, ready for review

#22 generateResponsiveStyles Formalization
  package-lock.json
  src/utils/generateResponsiveStyles.js
  tests/utils/generateResponsiveStyles/index.js
Labels: 1pt, ready for review

#3 View
  docs/pages/API/View/index.js
  docs/pages/API/index.js
  docs/pages/API/style.less
  docs/pages/Tests/index.js
  docs/specimens/ViewBasic/index.js
  docs/specimens/ViewKitchenSink/index.js
  package-lock.json
  src/View/index.js
  src/index.js
  src/utils/forwardRef.js
  tests/utils/forwardRef/index.js
  tests/visual/View.js
  tests/visual/screenshots/View.js/View - Kitchen Sink.snap.png
Labels: 3pt, ready for review

#21 Text Updates
  docs/pages/API/Text/index.js
  docs/pages/Tests/index.js
  docs/specimens/TextTransforms/index.js
  src/Text/index.js
  tests/components/Text/__snapshots__/index.js.snap
  tests/components/Text/index.js
  tests/visual/Text.js
  tests/visual/screenshots/Text.js/Text Sizes.snap.png
  tests/visual/screenshots/Text.js/Text Transforms.snap.png
Labels: 2pt, ready for review
